### ISSUE TITLE
question about test, thanks you 

### ISSUE THREAD

**Issue by nuist-xinyu** [Tencent/MedicalNet#38]
(MedicalNet) xinyu@xinyu-MS-7B89:~/MedicalNet-master$ python test.py --gpu_id 0 --resume_path trails/models/resnet_50_epoch_110_batch_0.pth.tar --img_list data/val.txt
/home/xinyu/MedicalNet-master/models/resnet.py:173: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  m.weight = nn.init.kaiming_normal(m.weight, mode='fan_out')
Processing 2 datas
./data/MRBrainS18/images/070.nii.gz
./data/MRBrainS18/images/1.nii.gz
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument
Traceback (most recent call last):
  File "test.py", line 92, in <module>
    masks = test(data_loader, net, img_names, sets)
  File "test.py", line 67, in test
    mask = ndimage.interpolation.zoom(mask, scale, order=1)
  File "/home/xinyu/anaconda3/lib/python3.6/site-packages/scipy/ndimage/interpolation.py", line 591, in zoom
    input = numpy.asarray(input)
  File "/home/xinyu/anaconda3/lib/python3.6/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home/xinyu/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 458, in __array__
    return self.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by SUN115AM** [comment]
it could be simply fixed by using cpu to convert Tensor to numpy data before giving it to scipy.ndimage. zoom. I guess this may caused by version incompatible between numpy and scipy.
Line 65, change 'mask = probs[0]' to  'mask = probs[0].cpu().numpy()' should be helpful.
